import { readFile, writeFile } from "node:fs/promises";
import { examples, contacts, articles } from "../examples/catalog.js";
import { watercolorSlots } from "../examples/watercolors.js";
import { previewTheme } from "../examples/preview-themes.js";

const artworks = new Map(JSON.parse(await readFile(new URL("../examples/assets/watercolors/sources.json", import.meta.url), "utf8")).map(art => [art.id, art]));

const esc = value => String(value).replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;");
const preview = (kind, cls = "") => `<img class="device-preview ${cls}" src="/examples/assets/previews/${kind}.jpg" alt="" width="1080" height="646" draggable="false">`;
const cardColors = kind => {
  const { caption, border, shadow } = previewTheme(kind);
  return `--preview-caption:${caption};--preview-border:${border};--preview-shadow:${shadow}`;
};
const image = (slot, alt, cls = "", extra = "") => {
  const art = artworks.get(watercolorSlots[slot]);
  if (!art) throw new Error(`Missing watercolor for image slot: ${slot}`);
  const description = alt ? `Watercolor: ${art.title} by ${art.artist_display.split("\n")[0]}` : "";
  return `<img class="${cls}" src="/examples/assets/watercolors/${art.file}" alt="${esc(description)}" data-watercolor-id="${art.id}" draggable="false" ${extra}>`;
};
const icon = (type, cls = "") => {
  const paths = { cross: '<path d="m6 6 12 12M18 6 6 18"/>', down: '<path d="m6 9 6 6 6-6"/>', back: '<path d="m15 5-7 7 7 7"/>', play: '<path d="m8 4 12 8-12 8z" fill="currentColor" stroke="none"/>', pause: '<path d="M7 5v14M17 5v14" stroke-width="5"/>', next: '<path d="m4 5 10 7L4 19zM14 5v14M20 5v14"/>', heart: '<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>', chat: '<path d="M4 3h16v14H8l-4 4Z"/>', share: '<path d="M12 16V2m-4 4 4-4 4 4M5 11v10h14V11"/>', repeat: '<path d="m16 3 4 4-4 4M4 7h16M8 21l-4-4 4-4m12 4H4"/>', grid: '<path d="M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z"/>', home: '<path d="m3 10 9-8 9 8v11H3Zm6 11v-8h6v8"/>', chart: '<path d="M4 20v-6m5 6V9m5 11V5m5 15V1M2 10l6-6 5 2 8-5"/>', people: '<circle cx="9" cy="7" r="4"/><path d="M1 22v-3a8 8 0 0 1 16 0v3m-1-19a4 4 0 0 1 0 8m3 4a6 6 0 0 1 4 7"/>', gear: '<circle cx="12" cy="12" r="4"/><path d="m9 2 6 0 1 4 4 1 2 5-3 3 0 4-5 3-3-3-4 0-3-5 3-3 0-4Z"/>' };
  return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type] || paths.grid}</svg>`;
};
// Filled playback glyphs use the same 20px geometry as the reference player.
const playerIcon = (type, cls = "") => {
  const paths = {
    play: '<path d="M6.3 2.84A1.5 1.5 0 0 0 4 4.11v11.78a1.5 1.5 0 0 0 2.3 1.27l9.344-5.891a1.5 1.5 0 0 0 0-2.538L6.3 2.841Z"/>',
    pause: '<rect x="4" y="3" width="4" height="14" rx="1.5"/><rect x="12" y="3" width="4" height="14" rx="1.5"/>',
    next: '<path d="M3.288 4.818A1.5 1.5 0 0 0 1 6.095v7.81a1.5 1.5 0 0 0 2.288 1.276l6.323-3.905c.155-.096.285-.213.389-.344v2.973a1.5 1.5 0 0 0 2.288 1.276l6.323-3.905a1.5 1.5 0 0 0 0-2.552l-6.323-3.906A1.5 1.5 0 0 0 10 6.095v2.972a1.506 1.506 0 0 0-.389-.343L3.288 4.818Z"/>'
  };
  return `<svg class="${cls}" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">${paths[type]}</svg>`;
};
const close = (type = "cross", label = "Dismiss Sheet", cls = "") => `<button type="button" data-sheet-close aria-label="${label}" class="dismiss ${cls}">${icon(type, cls === "profile-dismiss" && type === "cross" ? "desktop-dismiss" : "")}${cls === "profile-dismiss" && type === "cross" ? icon("down", "mobile-dismiss") : ""}</button>`;
const handle = (label = "Dismiss", action = "close") => `<button type="button" data-sheet-handle ${action === "close" ? "data-sheet-close" : `data-presentation-action="${action}"`} class="handle" aria-label="${label}"></button>`;
const action = label => `<button type="button" data-sheet-close class="primary-action">${label}</button>`;
const sheet = (id, kind, content, extra = "") => `<div id="${id}" data-controller="sheet" data-presentation="${kind}" ${extra}><div data-sheet-view hidden><div data-sheet-backdrop></div><section data-sheet-content class="example-sheet ${kind}-sheet" aria-label="${examples[id]?.[0] || (kind === "parallax" ? "Parallax Page" : id === "lightbox-comments" ? "Comments" : id.startsWith("depth") ? "Sheet with Depth" : "Sheet with Stacking")}">${content}</section></div></div>`;
const compact = (id, kind, title, description, photo, alt) => sheet(id, kind,
  `${kind === "top" ? close() : handle()}<div class="compact-body" data-sheet-body>${kind === "top" ? `<h2>${title}</h2>` : ""}${image(photo, alt, "compact-image")}<div class="compact-info">${kind !== "top" ? `<h2>${title}</h2>` : ""}<p>${description}</p></div>${action(kind === "top" ? "Book it Now" : "Got it")}</div>`);
const sidebarGroups = [["Dashboard", ["Overview", "Analytics", "Recent Activity"]], ["Projects", ["All Projects", "My Projects", "Archived Projects", "Create New Project"]], ["Teams", ["Team Members", "Roles & Permissions", "Invite Members", "Team Settings"]], ["Settings", ["Account Settings", "Profile Settings", "Billing Information", "Integrations", "Notifications"]], ["Support", ["Help Center", "FAQs", "Contact Support", "Feedback"]]];
const postTexts = [
  "A fresh notebook, a quiet morning, and a new idea to explore. Some days the smallest observation becomes the beginning of a story. Looking forward to seeing where this one goes!",
  "Spent a little time outside today. There is something about an unfamiliar path and a change of scenery that makes room for new ideas.",
  "The best part of a good book is sharing it with someone else. What have you been reading lately? I am making a list for the weekend. 📚",
  "A few moments from the studio this afternoon. Still learning, still experimenting, and enjoying the process as much as the finished work."
];
function profile(id, name, photo, cover, next, depth = false) {
  const username = name.toLowerCase().replaceAll(" ", "");
  const sophie = photo === "sophie";
  const posts = [photo, "olivia", photo, "liam", photo, "ava", "isabella", "sophia", "amelia", "james"].map((person, i) => {
    const displayName = person === photo ? name : contacts.find(c => c[0] === person)[1];
    return `<article class="post">${image(person, `${displayName}'s profile picture`, "post-avatar")}<div><div class="post-heading"><strong>${displayName}</strong> <span>@${displayName.toLowerCase().replaceAll(" ", "")} · ${i * 2 + 1}h</span></div><p>${postTexts[i % postTexts.length]}</p><div class="post-actions"><span>${icon("chat")} ${28 - i}</span><span>${icon("repeat")} ${10 + i}</span><span>${icon("heart")} ${75 - i}</span><span>${icon("share")}</span></div></div></article>`;
  }).join("");
  return sheet(id, depth ? "depth" : "stacking", `<div class="profile-scroll" data-sheet-body>${image(cover, "Profile cover", "profile-cover")}${image(photo, name, "profile-avatar")}<div class="profile-info"><h2>${name}</h2><p class="username">@${username}</p><p class="metrics"><span><b>${sophie ? 465 : 387}</b> followers</span><span><b>${sophie ? 239 : 453}</b> following</span><span><b>${sophie ? 47 : 64}</b> posts</span></p><p class="bio">${sophie ? "Author of captivating contemporary fiction.<br>Creating stories that resonate." : "Storyteller, dreamer, and lover of words.<br>Crafting narratives that inspire and connect."}</p></div><div class="posts">${posts}</div>${next ? `<button class="related-example" data-sheet-open="${next}" aria-label="Open ${depth ? "the next depth layer" : "the next stacking layer"}">${preview(depth ? "depth" : "stacking")}<strong>Sheet with ${depth ? "Depth" : "Stacking"}</strong></button>` : ""}</div><div class="profile-topbar">${close(depth ? "down" : "cross", "Dismiss Sheet", "profile-dismiss")}<span>${name}</span></div>`);
}
const articleText = [
  "Every place holds details that are easy to miss when we move too quickly. A change in the light, a familiar shape seen from another angle, or a moment of quiet can give an ordinary day a different character. Taking time to notice those details is often the beginning of a new idea. This is a story about paying attention, following a small curiosity, and making space for what comes next.",
  "There is no single route through a creative life. Some days call for careful planning; others reward a little wandering. The useful thing is to stay open to both. We learn through repetition, but we also learn by stepping outside a routine and noticing what changes. A conversation, a walk, or an afternoon spent trying something unfamiliar can bring an unexpected sense of direction.",
  "The most lasting experiences tend to arrive without much ceremony. We remember a particular color, the sound of a room, or the people who were there. Those impressions become part of how we understand a place. Returning later, we may find that the place has changed, or that we have. Either way, there is always something more to see."
];
function article(id, next = null) {
  const key = id === "parallax-child" ? "parallax" : id;
  const [title, subtitle, author, photo, alt] = articles[id];
  const kind = examples[key][1];
  const bar = key === "page-bottom" ? '<header class="article-bar"><button data-sheet-close>Close</button></header>' : key === "parallax" ? `<header class="article-bar parallax-bar">${close("back", "Back")}<span>${title}</span></header>` : "";
  return sheet(id, kind, `${bar}<div data-sheet-body ${kind === "parallax" ? "data-sheet-motion" : ""} class="article-scroll"><article class="reading-article">${image(photo, alt, "article-cover")}<div class="article-copy"><h1>${title}</h1><h2>${subtitle}</h2><p class="byline">by <span>${author}</span></p><div class="article-prose">${Array.from({length:10},(_,i)=>`<p>${articleText[i % 3]}</p>`).join("")}</div>${next ? `<button data-sheet-open="${next}" class="related-example">${preview("parallax")}<strong>Parallax Page</strong></button>` : ""}</div>${key === "long" ? close() : ""}</article></div>${key === "page-sheet" ? close() : ""}`);
}
const fields = [["Name", "The name displayed on the product's card.", "TrailBlazer Runners"], ["Brand", "The brand of the product.", "NatureStride"], ["Type", 'The type of the product (e.g. “t-shirt”, “pants”).', "Footwear"], ["Price", "The price of the product (€).", "149"]];
const comments = ["The view is absolutely breathtaking! 🌅 The combination of the city and the sea is mesmerizing.", "Amazing! 🌊", "A perfect place to slow down and watch the water. The colors are incredible; I would love to visit one day. ✨", "The contrast between the lively town and that calm blue sea is beautiful.", "This looks like a wonderful place for a weekend away. Adding it to my list! 🎒🌊"];
const commentList = () => contacts.map(([photo,name],i)=>`<article class="comment">${image(photo, "Profile picture")}<div><strong>${name}</strong><p>${comments[i%comments.length]}</p></div></article>`).join("");
const markup = [
  compact("basic", "bottom", "Activity Added to Your Calendar", "Your activity has been successfully scheduled. We'll send you a reminder as the date approaches.", "tennis", "Tennis racket and ball"),
  compact("top", "top", "Serene Haven is Available", "Your dream home, Serene Haven, is ready for you. A rare blend of luxury and charm—don't miss it!", "house", "Nice houses and blue sky"),
  compact("detached", "detached", "Your Meal is Coming", "Your food is on its way and will arrive soon! Sit back and get ready to enjoy your meal.", "meal", "Meal"),
  sheet("card", "card", `${close()}<div class="card-scroll" data-sheet-body>${image("paint", "Paint brushes", "card-image")}<div class="card-info"><h2>Paint and Sip</h2><p>Join our art workshop and let your imagination flow. Paint, create, and have fun.</p>${action("Reserve Spot")}</div></div>`),
  sheet("right", "sidebar", `${close("cross", "Close Sidebar example", "visually-hidden-until-focus")}<header class="organization">${image("acme", "Acme logo")}<strong>Acme Inc.</strong><span>support@acme.com</span></header><div class="sidebar-scroll" data-sheet-body>${sidebarGroups.map(([heading,items])=>`<section><h3>${heading}</h3><ul>${items.map((label,i)=>`<li><button data-sidebar-item data-sheet-drag>${icon(["grid","chart","home","people","gear"][i % 5])}<span>${label}</span></button></li>`).join("")}</ul></section>`).join("")}</div>`),
  sheet("toast", "toast", `<div class="toast-message" role="status">${image("luca", "Profile picture of a man")}<div><h2>Message from Luca</h2><p>How about Japanese? I'm good to meet up at 8.</p></div></div>`),
  profile("stacked", "Erik Johansson", "erik", "architecture", "child"),
  profile("child", "Sophie Dubois", "sophie", "stacking-child-cover", null),
  sheet("persistent", "persistent", `<div class="player-mini">${image("barcelona", "Album cover")}<div><strong>Barcelona Dreams</strong><span>Eira Voss</span></div><button class="expand-player" data-presentation-action="expand" aria-label="Expand Sheet"></button><button class="play-toggle" data-presentation-action="play" aria-label="Play" aria-pressed="false">${playerIcon("play")}${playerIcon("pause", "pause-icon")}</button></div><div class="player-full">${handle("Collapse sheet", "collapse")}${close("cross")}<div class="player-layout">${image("barcelona", "Album cover", "album-cover")}<div class="player-controls"><div class="track-name"><strong>Barcelona Dreams</strong><span>Eira Voss</span></div><input type="range" min="0" max="1000" value="700" aria-label="Track position"></div><div class="transport"><button data-presentation-action="previous-track" aria-label="Previous track">${playerIcon("next", "reverse")}</button><button class="play-toggle" data-presentation-action="play" aria-label="Play" aria-pressed="false">${playerIcon("play")}${playerIcon("pause", "pause-icon")}</button><button data-presentation-action="next-track" aria-label="Next track">${playerIcon("next")}</button></div></div></div>`, 'data-turbo-permanent'),
  sheet("detents", "detents", `<header class="contacts-header">${handle("Cycle", "cycle")}<input type="search" aria-label="Search for a contact" placeholder="Search for a contact"></header><div data-sheet-body class="contacts-list">${contacts.map(([photo,name,company])=>`<div class="contact" data-contact="${esc(name.toLowerCase())}">${image(photo,"Profile picture")}<div><strong>${name}</strong><span>${company}</span></div></div>`).join("")}<p class="empty-contacts" hidden>No contacts found.</p></div>`),
  profile("depth", "Sophie Dubois", "sophie", "mountains", "depth-child", true),
  profile("depth-child", "Erik Johansson", "erik", "depth-child-cover", "depth-third", true),
  profile("depth-third", "Sophie Dubois", "sophie", "depth-third-cover", null, true),
  sheet("keyboard", "keyboard", `<header class="product-header"><button data-sheet-close>Cancel</button><h2>Edit Product</h2><button data-presentation-action="save">Save</button></header><div data-sheet-body class="product-scroll"><div class="product-images" data-sheet-no-drag>${[0,1,2,3].map(i=>image(`shoe${i}`,`Product Image ${i}`)).join("")}</div><div class="product-details"><h3>Product details</h3><form class="product-form">${fields.map(([name,help,value])=>`<label class="product-field"><strong>${name}</strong><span>${esc(help)}</span><input name="${name.toLowerCase()}" type="${name==='Price'?'number':'text'}" value="${value}" required></label>`).join("")}<fieldset class="product-colors"><legend>Colors</legend><p>The main colors of the product.</p>${["#d1a74c", "#7dd42c", "#ffffff"].map((color,i)=>`<input type="color" value="${color}" aria-label="${['Primary','Secondary','Tertiary'][i]} color">`).join("")}</fieldset><label class="product-field description-field"><strong>Description</strong><span>The description that will shown on the product's page.</span><textarea rows="5" name="description">Experience unmatched comfort and performance NatureStride's TrailBlazer Runners.</textarea></label></form></div></div>`),
  sheet("lightbox", "lightbox", `<div class="lightbox-stage" data-sheet-motion>${image("santorini", "Santorin", "lightbox-image")}</div>${close("cross").replace("data-sheet-close", "data-sheet-close data-sheet-motion-fade")}<button class="comments-trigger" data-sheet-open="lightbox-comments" data-sheet-motion-fade>${icon("chat")}Comments</button><aside class="comments" data-sheet-motion-fade><h2>Comments</h2><div data-sheet-body class="comments-scroll">${commentList()}</div></aside>`),
  sheet("lightbox-comments", "mobile-comments", `<header class="comments-header">${close("down", "Dismiss Comments")}<h2>Comments</h2></header><div class="comments-scroll" data-sheet-body>${commentList()}</div>`),
  article("parallax", "parallax-child"), article("parallax-child"), article("long"), article("page-sheet"), article("page-bottom")
].join("\n");
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Hotwire Sheets · Native-like swipeable sheets for Hotwire</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/app/assets/stylesheets/hotwire_sheets.css"><link rel="stylesheet" href="/examples/gallery.css"><link rel="stylesheet" href="/examples/site.css"><script type="importmap">{"imports":{"@hotwired/stimulus":"/node_modules/@hotwired/stimulus/dist/stimulus.js","@hotwired/turbo":"/node_modules/@hotwired/turbo/dist/turbo.es2017-esm.js","hotwire-sheets":"/app/assets/javascripts/hotwire_sheets.js","hotwire-sheets/stimulus":"/app/assets/javascripts/hotwire_sheets_stimulus.js"}}</script><script type="module" src="/examples/gallery.js"></script></head><body><main id="page"><nav class="gallery-bar" aria-label="Main navigation"><a href="/" class="gallery-brand" data-turbo="false">Hotwire Sheets <span>0.1.0</span></a><div class="gallery-nav"><a href="/docs" data-turbo="false" class="docs-link">Docs</a></div></nav><div class="gallery-content"><header class="gallery-intro"><div class="gallery-meta">RAILS · HOTWIRE · STIMULUS</div><h1>Native‑like <em>swipeable sheets</em> for Hotwire</h1><p>Build fluid, swipeable interfaces with Rails, Stimulus, and Turbo.</p><a class="get-started" href="/docs" data-turbo="false">Get started</a></header><h2 class="gallery-section-title" id="examples-heading">Examples</h2><section class="cards" id="examples" aria-labelledby="examples-heading">${Object.entries(examples).map(([id, [name, kind]])=>`<button type="button" class="example-card" style="${cardColors(kind)}" data-sheet-open="${id}" aria-label="${name}">${preview(kind, "preview")}<strong>${name}</strong></button>`).join("")}</section><footer class="gallery-footer">Hotwire Sheets · Rails + Stimulus <a href="/docs" data-turbo="false">Developer documentation</a></footer></div></main>${markup}</body></html>`;
await writeFile(new URL("../examples/gallery.html", import.meta.url), html);
console.log("Built all 16 reference presentations.");
