import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
const styles = await readFile("app/assets/stylesheets/hotwire_sheets.css", "utf8");
await writeFile("app/assets/stylesheets/hotwire_sheets_layered.css", `/* Generated by npm run build. */\n@layer hotwire-sheets {\n${styles}\n}\n`);
await build({
  entryPoints: { hotwire_sheets: "src/index.js", hotwire_sheets_stimulus: "src/stimulus/index.js" },
  outdir: "app/assets/javascripts", bundle: true, format: "esm", target: ["es2022"],
  external: ["@hotwired/stimulus"], minify: false,
  plugins: [{ name: "shared-core", setup(build) {
    build.onResolve({ filter: /^\.\.\/index\.js$/ }, (args) => {
      if (args.importer.includes("/stimulus/")) return { path: "hotwire-sheets", external: true };
    });
  } }],
  banner: { js: "/* Hotwire Sheets — MIT. Generated by npm run build; edit src/ instead. */" }
});
